apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-service
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-service
            image: your-docker-repo/update-service:latest
            env:
            - name: DATABASE_URL
              value: "your-mysql-connection-string"
          restartPolicy: OnFailure
