apiVersion: v1
kind: Service
metadata:
  name: urlinfo-service
spec:
  selector:
    app: urlinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP  # Can be changed to LoadBalancer if external cloud LB is used
