apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-service
  template:
    metadata:
      labels:
        app: update-service
    spec:
      containers:
      - name: update-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: DATABASE_URL
          value: "your-mysql-connection-string"
        command: ["python"]
        args: ["src/update/update_service.py"]
